# NumPy - Numerical Python

Advantages of Numppy Arrays:
1. Allows several Mathmetical Operations
2. Faster Operations

In [1]:
import numpy as np

#### List vs NumPy - Time Taken

In [3]:
from time import process_time

**Time taken by a list**

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)


0.0004449910000001722


In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00013514999999930666


# NumPy Arrays

In [6]:
# List
list_1 = [1,2,3,4,5]
print(list_1)
type(list_1)

[1, 2, 3, 4, 5]


list

In [7]:
np_arrays = np.array([1,2,3,4,5])
print(np_arrays)
type(np_arrays)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# Create a 1 Dimention array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [9]:
a.shape

(5,)

In [10]:
a.size

5

In [12]:
b = np.array([(1,2,3,4,5), (6,7,8,9,10)])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
b.shape

(2, 5)

In [15]:
b.size

10

In [17]:
c = np.array([(1,2,3,4), (5,6,7,8)], dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [20]:
c.shape

(2, 4)

In [21]:
c.size

8

#### Initial Placeholders in numpy arrays

In [24]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
# Create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
# Create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.41221731 0.51508568 0.35229322 0.16649488]
 [0.02212085 0.14432642 0.14709633 0.78644294]
 [0.45538645 0.68740164 0.76376581 0.93947416]]


#### Randint
**Syntax:**
```python
np.random.randint(Lower_bound, Upper_bound, (rows, columns))

In [30]:
# Create a random integer values array within a specific range
c = np.random.randint(10,100, (3,5))
print(c)

[[99 80 69 88 51]
 [20 19 18 61 39]
 [56 90 67 20 27]]


In [58]:
dice = np.random.randint(1, 6)
print(dice)

5


In [67]:
# Create a array of evenly spaced values ---> Specifying the number of values required
d = np.linspace(10,30,5)
print(d)


[10. 15. 20. 25. 30.]


In [68]:
# Create a array of evenly spaced values --> Specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [71]:
# Convert a list to a numpy array
list_2 = [10,20,30,40,50]

np_array = np.asarray(list_2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

# Analysing a numpy array

In [73]:
c = np.random.randint(10,90,(5,5))
print(c)

[[29 57 42 27 33]
 [10 19 39 29 60]
 [27 16 74 55 16]
 [81 45 38 18 10]
 [10 49 75 12 86]]


In [74]:
# Array Dimension
print(c.shape)

(5, 5)


In [75]:
# Number of dimensions
print(c.ndim)

2


In [76]:
# Number of elements in an array
print(c.size)

25


In [77]:
# Checking the data type of the values in the array
print(c.dtype)

int64


# Mathematical Operatons on a np array

In [78]:
list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]

print(list_1 + list_2)    # Concatenate of Joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [79]:
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(0, 20, (3,3))

In [81]:
print(a)

[[9 6 0]
 [7 2 8]
 [2 5 2]]


In [82]:
print(b)

[[14  7  6]
 [ 4 19  1]
 [18 16 13]]


In [83]:
print(a+b)

[[23 13  6]
 [11 21  9]
 [20 21 15]]


In [84]:
print(a-b)

[[ -5  -1  -6]
 [  3 -17   7]
 [-16 -11 -11]]


In [85]:
print(a*b)

[[126  42   0]
 [ 28  38   8]
 [ 36  80  26]]


In [86]:
print(a/b)

[[0.64285714 0.85714286 0.        ]
 [1.75       0.10526316 8.        ]
 [0.11111111 0.3125     0.15384615]]


In [87]:
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(0, 20, (3,3))

In [88]:
print(a)

[[6 1 3]
 [5 0 3]
 [4 1 9]]


In [89]:
print(b)

[[10 19  5]
 [10 12  2]
 [ 2 13 16]]


In [90]:
print(np.add(a,b))

[[16 20  8]
 [15 12  5]
 [ 6 14 25]]


In [91]:
print(np.subtract(a,b))

[[ -4 -18  -2]
 [ -5 -12   1]
 [  2 -12  -7]]


In [92]:
print(np.multiply(a,b))

[[ 60  19  15]
 [ 50   0   6]
 [  8  13 144]]


In [93]:
print(np.divide(a,b))

[[0.6        0.05263158 0.6       ]
 [0.5        0.         1.5       ]
 [2.         0.07692308 0.5625    ]]


#### Array Manipulation

In [98]:
array = np.random.randint(0,10, (2,3))
print(array)
print(array.shape)

[[9 1 8]
 [8 9 5]]
(2, 3)


In [99]:
# Transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 8]
 [1 9]
 [8 5]]
(3, 2)


In [100]:
array = np.random.randint(0,10, (2,3))
print(array)
print(array.shape)

[[4 5 2]
 [7 5 9]]
(2, 3)


In [101]:
trans_2 = array.T
print(trans_2)
print(trans_2.shape)

[[4 7]
 [5 5]
 [2 9]]
(3, 2)


In [102]:
# Reshaping a array
array_2 = np.random.randint(0,10, (2,3))
print(array_2)
print(array_2.shape)

[[3 0 6]
 [6 8 7]]
(2, 3)


In [104]:
array_3 = array_2.reshape(3,2)
print(array_3)
print(array_3.shape)

[[3 0]
 [6 6]
 [8 7]]
(3, 2)
